name = "vortex-settlement-worker"
main = "src/index.ts"
compatibility_date = "2024-03-20"

[triggers]
crons = ["* * * * *"] # Executes every 1 minute

[vars]
GENLAYER_NETWORK = "studionet"
VORTEX_CONTRACT_ADDRESS = "0x439A57ae7163a9100fCA2a04dfB827475Db3513e"
SETTLEMENT_SAFETY_GRACE_PERIOD_SECONDS = "120"
